---
permalink: config-admin/anomalies.html 
sidebar: sidebar 
keywords:  
summary: 'La section anomalies, qui s"affiche uniquement sur une page de ressources d"application lorsque le moteur de détection des anomalies est installé, vous permet d"identifier la plage de charges de travail normales d"une application et de déterminer si les modifications de performances sont en dehors des niveaux attendus.' 
---
= Anomalies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La section anomalies, qui s'affiche uniquement sur une page de ressources d'application lorsque le moteur de détection des anomalies est installé, vous permet d'identifier la plage de charges de travail normales d'une application et de déterminer si les modifications de performances sont en dehors des niveaux attendus.

L'analyse des anomalies offre une visibilité proactive sur l'infrastructure sur laquelle reposent les applications stratégiques et signale les anomalies de performance avant qu'elles ne deviennent des interruptions de service. Le moteur de détection des anomalies des applications analyse les indicateurs de performance recueillis par Insight et identifie les anomalies dans l'infrastructure applicative. Les anomalies sont des éléments, des événements ou des observations qui ne sont pas conformes à un modèle prévu ou à d'autres éléments. Avec la détection des anomalies, vous pouvez :

* Surveiller les applications critiques sélectionnées.
* Identifiez les changements significatifs dans le comportement de l'infrastructure applicative.
* Suivi d'une application sur l'ensemble de la pile et sur plusieurs compteurs.
* Diagnostiquez la cause des événements récurrents périodiques dans une charge de travail applicative.
* Fournir un ensemble plus complet d'informations par rapport aux données des compteurs de performances utilisant des valeurs de seuil statiques.
* Surveillance améliorée en mode réactif avec une vue de bout en bout de la topologie et la capacité de se concentrer sur les comportements anormaux les plus anormaux d'un ensemble de données.

