---
permalink: config-admin/anomaly-detection-monitoring-status.html 
sidebar: sidebar 
keywords:  
summary: 'L"état de surveillance de la détection des anomalies est disponible dans les requêtes d"application, les widgets et les pages de ressources.' 
---
= État de surveillance de la détection des anomalies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'état de surveillance de la détection des anomalies est disponible dans les requêtes d'application, les widgets et les pages de ressources.



== État de surveillance de la détection des anomalies

Pour chaque application, vous verrez l'un des éléments suivants :

* *OK*
+
Aucun problème n'est détecté.

* *Apprentissage*
+
Le serveur de détection des anomalies récupère jusqu'à 14 jours de données de performance et les charge dans le moteur de détection des anomalies.

* *Dépasse les actifs maximaux*
+
Le nombre maximal d'actifs surveillés pour une application a été dépassé. Un maximum de 4000 ressources peuvent être surveillées pour une application. La surveillance est suspendue jusqu'à ce que le nombre d'actifs soit inférieur ou égal à 4000. Réduire le nombre de ressources surveillées pour continuer la surveillance.

* *Échec*
+
La connexion au serveur de détection des anomalies a échoué.

* *Non surveillé*
+
La surveillance est désactivée pour l'application. Dans les requêtes et les widgets, ce champ est laissé vide.


