---
permalink: config-admin/brocade-fc-switch-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight utilise la source de données Brocade FC Switch \(SSH\) pour détecter l"inventaire des commutateurs Brocade ou des commutateurs portant une nouvelle marque exécutant le micrologiciel factorisé du système d"exploitation \(FOS\) version 4.2 ou ultérieure. Les périphériques en mode commutateur FC et passerelle d"accès sont pris en charge.' 
---
= Source de données du commutateur FC Brocade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight utilise la source de données Brocade FC Switch (SSH) pour détecter l'inventaire des commutateurs Brocade ou des commutateurs rebrandés exécutant le micrologiciel FOS (système d'exploitation factorisé) version 4.2 ou ultérieure. Les périphériques en mode commutateur FC et passerelle d'accès sont pris en charge.



== Terminologie

OnCommand Insight acquiert les informations d'inventaire suivantes à partir de la source de données du commutateur FC Brocade. Pour chaque type de ressource acquis par Insight, la terminologie la plus courante utilisée pour cette ressource est indiquée. Lors de l'affichage ou du dépannage de cette source de données, gardez à l'esprit la terminologie suivante :

|===


| Terme du fournisseur/modèle | Terme Insight 


 a| 
Commutateur
 a| 
Commutateur



 a| 
Port
 a| 
Port



 a| 
Structure virtuelle, structure physique
 a| 
Structure



 a| 
Zone
 a| 
Zone



 a| 
Commutateur logique
 a| 
Commutateur logique



 a| 
Zone LSAN
 a| 
Zone IVR

|===
[NOTE]
====
Il s'agit uniquement de mappages terminologiques courants et peuvent ne pas représenter tous les cas pour cette source de données.

====


== De formation

* L'unité d'acquisition (locale ou distante) initie les connexions au port TCP 22 sur les commutateurs Brocade pour collecter les données d'inventaire. L'UA initiera également les connexions au port UDP 161 pour la collecte des données de performances.
* Il doit y avoir une connectivité IP à tous les commutateurs de la structure. Si vous cochez la case détecter tous les switchs dans la structure, OCI identifie tous les switchs de la structure. Toutefois, il nécessite une connectivité IP pour les découvrir.
* Le même compte est nécessaire au niveau global pour tous les commutateurs du maillage. Vous pouvez utiliser PuTTY (émulateur de terminal open source) pour confirmer l'accès.
* Si la licence Perform est installée, les ports 161 et 162 doivent être ouverts à tous les commutateurs de la structure pour l'interrogation des performances SNMP.
* Chaîne de communauté en lecture seule SNMP




== Configuration

|===


| Champ | Description 


 a| 
IP du commutateur
 a| 
Adresse IP ou nom de domaine complet du commutateur



 a| 
Nom d'utilisateur
 a| 
Nom d'utilisateur du commutateur



 a| 
Mot de passe
 a| 
Mot de passe utilisé pour le commutateur



 a| 
Version SNMP
 a| 
Version SNMP



 a| 
Chaîne de communauté SNMP
 a| 
Chaîne de communauté en lecture seule SNMP utilisée pour accéder au commutateur



 a| 
Nom d'utilisateur SNMP
 a| 
Nom d'utilisateur du protocole de version SNMP (s'applique uniquement à SNMP v3)



 a| 
Mot de passe SNMP
 a| 
Mot de passe du protocole de version SNMP (s'applique uniquement à SNMP v3)

|===


== Configuration avancée

|===


| Champ | Description 


 a| 
Nom de la structure
 a| 
Nom de la structure à signaler par la source de données. Laissez vide pour signaler le nom de la structure comme WWN.



 a| 
Exclure les périphériques
 a| 
Liste des ID de périphériques séparés par des virgules à exclure de l'interrogation



 a| 
Intervalle d'interrogation des stocks (min)
 a| 
Intervalle entre les sondages d'inventaire (15 minutes par défaut)



 a| 
Délai (s)
 a| 
Délai d'expiration de la connexion (par défaut : 30 secondes)



 a| 
Délai d'attente de la bannière (s)
 a| 
Délai d'attente de bannière SSH (5 secondes par défaut)



 a| 
Domaines d'administration actifs
 a| 
Sélectionnez si vous utilisez des domaines Admin



 a| 
Récupérer les données MPR
 a| 
Sélectionnez cette option pour acquérir des données de routage à partir de votre routeur multiprotocole (MPR)



 a| 
Activer le recouvrement
 a| 
Sélectionnez cette option pour activer l'acquisition lors de la réception d'une interruption SNMP à partir du périphérique. Si vous sélectionnez Activer le recouvrement, vous devez également activer SNMP.



 a| 
Temps minimum entre les recouvrements (s)
 a| 
Temps minimum entre les tentatives d'acquisition déclenchées par des interruptions (10 secondes par défaut)



 a| 
Découvrir tous les commutateurs du tissu
 a| 
Sélectionnez pour découvrir tous les commutateurs de la structure



 a| 
Sélectionnez favoriser l'HBA vs Alias de zone
 a| 
Choisissez de favoriser les alias de HBA ou de zone



 a| 
Intervalle d'interrogation des performances (s)
 a| 
Intervalle entre les sondages de performances (300 secondes par défaut)



 a| 
Protocole d'autorisation SNMP
 a| 
Protocole d'authentification SNMP (SNMP v3 uniquement)



 a| 
Protocole de confidentialité SNMP
 a| 
Protocole de confidentialité SNMP (SNMP v3 uniquement)



 a| 
Mot de passe de confidentialité SNMP
 a| 
Mot de passe de confidentialité SNMP (SNMP v3 uniquement)



 a| 
Nouvelles tentatives SNMP
 a| 
Nombre de tentatives de tentative SNMP



 a| 
Délai d'expiration SNMP (ms)
 a| 
SNMP timeout (5000 ms par défaut)

|===