---
permalink: config-admin/certificate-login-support.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight prend en charge l"utilisation de cartes à puce \(CAC\) et de certificats pour authentifier les utilisateurs se connectant aux serveurs Insight. Vous devez configurer le système pour activer ces fonctions.' 
---
= Prise en charge de la connexion par carte à puce et certificat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight prend en charge l'utilisation de cartes à puce (CAC) et de certificats pour authentifier les utilisateurs qui se connectent aux serveurs Insight. Vous devez configurer le système pour activer ces fonctions.

Après avoir configuré le système pour prendre en charge le contrôle d'admission des appels et les certificats, la navigation vers une nouvelle session de OnCommand Insight entraîne l'affichage d'une boîte de dialogue native qui fournit à l'utilisateur une liste de certificats personnels à choisir. Ces certificats sont filtrés en fonction de l'ensemble des certificats personnels émis par les autorités de certification approuvées par le serveur OnCommand Insight. Le plus souvent, il y a un seul choix. Par défaut, Internet Explorer ignore cette boîte de dialogue s'il n'y a qu'une seule option.

[NOTE]
====
Pour les utilisateurs CAC, les cartes à puce contiennent plusieurs certificats, dont un seul peut correspondre à l'autorité de certification approuvée. Le certificat CAC pour `identification` doit être utilisé.

====
[NOTE]
====
Pour obtenir les instructions les plus récentes sur les cartes CAC et les certificats, consultez les articles suivants de la base de connaissances (connexion au support requise) :

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight["Comment configurer l'authentification CAC (Common Access Card) pour OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse["Comment configurer l'authentification CAC (Common Access Card) pour l'entrepôt de données OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X["Comment créer et importer un certificat signé d'autorité de certification dans OnComand Insight et l'entrepôt de données OnCommand Insight 7.3.x."]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host["Comment créer un certificat auto-signé dans OnCommand Insight 7.3.X installé sur un hôte Windows"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later["Importation d'un certificat signé par l'autorité de certification Cognos dans l'entrepôt de données OnCommand 7.3.3 et versions ultérieures"]


====