---
permalink: config-admin/changing-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: 'Un utilisateur disposant de privilèges d"administrateur peut modifier le mot de passe de tout compte d"utilisateur OnCommand Insight défini sur le serveur local.' 
---
= Modification des mots de passe utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un utilisateur disposant de privilèges d'administrateur peut modifier le mot de passe de tout compte d'utilisateur OnCommand Insight défini sur le serveur local.



== Avant de commencer

Les éléments suivants doivent avoir été remplis :

* Notifications à toute personne se connectant au compte utilisateur que vous modifiez.
* Nouveau mot de passe à utiliser après cette modification.




== Description de la tâche

Lorsque vous utilisez cette méthode, vous ne pouvez pas modifier le mot de passe d'un utilisateur validé via LDAP.



== Étapes

. Connectez-vous avec des privilèges d'administrateur.
. Dans la barre d'outils Insight, cliquez sur *Admin*.
. Cliquez sur *Configuration*.
. Cliquez sur l'onglet *utilisateurs*.
. Recherchez la ligne qui affiche le compte utilisateur que vous souhaitez modifier.
. À droite des informations utilisateur, cliquez sur *Modifier le compte utilisateur*.
. Saisissez le nouveau *Mot de passe*, puis saisissez-le à nouveau dans le champ de vérification.
. Cliquez sur *Enregistrer*.

