---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: 'Les stratégies de sécurité peuvent vous obliger à modifier les mots de passe dans votre environnement OnCommand Insight. Certains mots de passe d"un serveur existent sur un serveur différent dans l"environnement, ce qui nécessite que vous modifiiez le mot de passe sur les deux serveurs. Par exemple, lorsque vous modifiez le mot de passe de l"utilisateur « Inventory » sur le serveur Insight Server, vous devez faire correspondre le mot de passe de l"utilisateur « Inventory » sur le connecteur du serveur Data Warehouse configuré pour ce serveur Insight Server.' 
---
= Modification des mots de passe des utilisateurs internes OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les stratégies de sécurité peuvent vous obliger à modifier les mots de passe dans votre environnement OnCommand Insight. Certains mots de passe d'un serveur existent sur un serveur différent dans l'environnement, ce qui nécessite que vous modifiiez le mot de passe sur les deux serveurs. Par exemple, lorsque vous modifiez le mot de passe utilisateur « Inventory » sur le serveur Insight Server, vous devez faire correspondre le mot de passe utilisateur « Inventory » sur le connecteur du serveur Data Warehouse configuré pour ce serveur Insight Server.



== Avant de commencer

[NOTE]
====
Vous devez comprendre les dépendances des comptes d'utilisateur avant de modifier les mots de passe. Si vous ne mettez pas à jour les mots de passe sur tous les serveurs requis, les problèmes de communication entre les composants Insight seront à l'origine de ces échecs.

====


== Description de la tâche

Le tableau suivant répertorie les mots de passe des utilisateurs internes pour Insight Server et répertorie les composants Insight qui ont des mots de passe dépendants qui doivent correspondre au nouveau mot de passe.

|===


| Mots de passe du serveur Insight | Modifications requises 


 a| 
_interne
 a| 



 a| 
acquisition
 a| 
LAU, RAU



 a| 
dwh_interne
 a| 
Entrepôt de données



 a| 
hôtes
 a| 



 a| 
inventaire
 a| 
Entrepôt de données



 a| 
racine
 a| 

|===
Le tableau suivant répertorie les mots de passe des utilisateurs internes pour l'entrepôt de données et répertorie les composants Insight qui ont des mots de passe dépendants qui doivent correspondre au nouveau mot de passe.

|===


| Mots de passe d'entrepôt de données | Modifications requises 


 a| 
cognos_admin
 a| 



 a| 
dwh
 a| 



 a| 
dwh_Internal (modifié à l'aide de l'interface utilisateur de configuration du connecteur du serveur)
 a| 
Serveur Insight



 a| 
dwhuser
 a| 



 a| 
hôtes
 a| 



 a| 
Inventaire (modifié à l'aide de l'interface utilisateur de configuration de Server Connector)
 a| 
Serveur Insight



 a| 
racine
 a| 

|===
*Modification des mots de passe dans l'interface utilisateur de configuration de la connexion au serveur DWH*

Le tableau suivant répertorie le mot de passe utilisateur POUR LAU et répertorie les composants Insight qui ont des mots de passe dépendants qui doivent correspondre au nouveau mot de passe.

|===


| Mots de passe LAU | Modifications requises 


 a| 
acquisition
 a| 
Insight Server, RAU

|===