---
permalink: config-admin/cognos-configuration-for-smart-card-and-certificate-login-7-3-10-and-later.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez modifier la configuration de l"entrepôt de données OnCommand Insight pour prendre en charge les connexions de carte à puce \(CAC\) et de certificat pour le serveur Cognos.' 
---
= Configuration de Cognos pour la connexion par carte à puce et certificat (OnCommand Insight 7.3.10 et versions ultérieures)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez modifier la configuration de l'entrepôt de données OnCommand Insight pour prendre en charge les connexions de carte à puce (CAC) et de certificat pour le serveur Cognos.



== Avant de commencer

Cette procédure concerne les systèmes exécutant OnCommand Insight 7.3.10 et versions ultérieures.

[NOTE]
====
Pour obtenir les instructions les plus récentes sur les cartes CAC et les certificats, consultez les articles suivants de la base de connaissances (connexion au support requise) :

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight["Comment configurer l'authentification CAC (Common Access Card) pour OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse["Comment configurer l'authentification CAC (Common Access Card) pour l'entrepôt de données OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X["Comment créer et importer un certificat signé d'autorité de certification dans OnComand Insight et l'entrepôt de données OnCommand Insight 7.3.x."]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host["Comment créer un certificat auto-signé dans OnCommand Insight 7.3.X installé sur un hôte Windows"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later["Importation d'un certificat signé par l'autorité de certification Cognos dans l'entrepôt de données OnCommand 7.3.3 et versions ultérieures"]


====


== Étapes

. Ajoutez des autorités de certification (AC) au magasin de certificats Cognos.
+
.. Dans une fenêtre de commande, accédez à `..\SANscreen\cognos\analytics\configuration\certs\`
.. Utilisez `keytool` l'utilitaire pour répertorier les autorités de certification de confiance : `..\..\ibm-jre\jre\bin\keytool.exe -list -keystore CAMKeystore.jks -storepass <password>


+
Le premier mot de chaque ligne indique l'alias de l'autorité de certification.

+
.. S'il n'existe aucun fichier approprié, fournissez un fichier de certificat d'autorité de certification, généralement un `.pem` fichier.
.. Pour inclure les autorités de certification du client avec des autorités de certification OnCommand Insight approuvées, rendez-vous sur `..\SANscreen\cognos\analytics\configuration\certs\`.
.. Utilisez le `keytool` utilitaire d'importation de `.pem` fichier : `..\..\ibm-jre\jre\bin\keytool.exe -importcert -keystore CAMKeystore.jks -alias my_alias -file 'path/to/my.pem' -v -trustcacerts`
+
`my_alias` Est généralement un alias qui identifie facilement l'autorité de certification dans l'``keytool -list``opération.

.. Lorsque vous êtes invité à entrer un mot de passe, entrez le mot de passe du fichier _/SANscreen/bin/cognos_info.dat_.
.. Réponse `yes` lorsque vous êtes invité à approuver le certificat.


. Pour activer le mode CAC, procédez comme suit :
+
.. Configurez la page de déconnexion CAC en procédant comme suit :
+
*** Se connecter au portail Cognos (l'utilisateur doit faire partie du groupe administrateurs système, c'est-à-dire cognos_admin)
*** (Uniquement pour 7.3.10 et 7.3.11) cliquez sur gérer \-> Configuration \-> système \-> sécurité
*** (Uniquement pour 7.3.10 et 7.3.11) Entrez cacLogout.html en regard de l'URL de redirection de déconnexion \-> appliquer
*** Fermez le navigateur.


.. L'exécution `..\SANscreen\bin\cognos_cac\enableCognosCAC.bat`
.. Démarrez le service IBM Cognos. Attendez que le service Cognos démarre.


. Pour désactiver le mode CAC, procédez comme suit :
+
.. L'exécution `..\SANscreen\bin\cognos_cac\disableCognosCAC.bat`
.. Démarrez le service IBM Cognos. Attendez que le service Cognos démarre.
.. (Uniquement pour 7.3.10 et 7.3.11) Déconfigurer la page de déconnexion CAC, en procédant comme suit :
+
*** Se connecter au portail Cognos (l'utilisateur doit faire partie du groupe administrateurs système, c'est-à-dire cognos_admin)
*** Cliquez sur gérer \-> Configuration \-> système \-> sécurité
*** Saisissez cacLogout.html par rapport à l'URL de redirection de déconnexion \-> appliquer
*** Fermez le navigateur.





