---
permalink: config-admin/data-source-patches.html 
sidebar: sidebar 
keywords:  
summary: 'Les correctifs de source de données corrigeant les problèmes avec les correctifs existants et vous permettent également d"ajouter facilement de nouveaux types de sources de données \(fournisseurs et modèles\). Pour chaque type de source de données de votre réseau, vous pouvez télécharger des correctifs de source de données. Vous pouvez également installer, tester et gérer le processus de correction. Cependant, un seul correctif peut être actif pour un type de source de données à la fois.' 
---
= Quels sont les correctifs de source de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les correctifs des sources de données corrigeant les problèmes avec les correctifs existants et vous permettent également d'ajouter facilement de nouveaux types de sources de données (fournisseurs et modèles). Pour chaque type de source de données de votre réseau, vous pouvez télécharger des correctifs de source de données. Vous pouvez également installer, tester et gérer le processus de correction. Cependant, un seul correctif peut être actif pour un type de source de données à la fois.

Pour chaque correctif, vous pouvez effectuer les tâches suivantes :

* Vérifiez la comparaison avant et après de chaque source de données recevant le correctif.
* Rédiger des commentaires pour expliquer les décisions ou résumer la recherche.
* Apportez des modifications à une source de données qui ne répond pas bien au correctif.
* Approuvez le correctif à valider sur votre serveur Insight.
* Restauration d'un patch qui ne fonctionne pas comme vous l'aviez prévu.
* Remplacez un patch défectueux par un autre.

