---
permalink: config-admin/dell-emc-powerstore-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Le collecteur de données Dell EMC PowerStore collecte les informations d"inventaire à partir du stockage Dell EMC PowerStore. Pour la configuration, le collecteur de données nécessite l"adresse IP des processeurs de stockage ainsi qu"un nom d"utilisateur et un mot de passe en lecture seule.' 
---
= Source de données Dell EMC PowerStore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le collecteur de données Dell EMC PowerStore collecte les informations d'inventaire à partir du stockage Dell EMC PowerStore. Pour la configuration, le collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.



== Terminologie

OnCommand Insight acquiert les informations d'inventaire suivantes à partir de la source de données EMC Data Domain. Pour chaque type de ressource acquis par Insight, la terminologie la plus courante utilisée pour cette ressource est indiquée. Lors de l'affichage ou du dépannage de cette source de données, gardez à l'esprit la terminologie suivante :

|===


| Terme du fournisseur/modèle | Terme Insight 


 a| 
hôte
 a| 
hôte



 a| 
host_volume_mapping
 a| 
host_volume_mapping



 a| 
Matériel (il a des disques sous objet "extra_details"): Lecteurs
 a| 
Disque



 a| 
Appliance
 a| 
Poolde stockage



 a| 
Cluster
 a| 
Baie de stockage



 a| 
Nœud
 a| 
StorageNode



 a| 
port fc
 a| 
Port



 a| 
volumétrie
 a| 
Volumétrie



 a| 
Volume interne
 a| 
système_fichiers



 a| 
Filesys
 a| 
Volume interne



 a| 
MTree
 a| 
Qtree



 a| 
Quota
 a| 
Quota



 a| 
Partage NFS et CIFS
 a| 
Fileshare

|===
[NOTE]
====
Il s'agit uniquement de mappages terminologiques courants et peuvent ne pas représenter tous les cas pour cette source de données.

====


== De formation

* Adresse IP ou nom de domaine complet du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule




== Numéro de série parent expliqué

Insight est généralement capable de communiquer le numéro de série de la baie de stockage ou les numéros de série de chaque nœud de stockage. Cependant, certaines architectures de baies de stockage ne s'alignent pas proprement sur cette configuration. Un cluster PowerStore peut être composé de 1-4 appliances et chaque appliance possède 2 nœuds. Si l'appliance elle-même possède un numéro de série, ce numéro ne correspond ni au numéro de série du cluster, ni aux nœuds.

L'attribut « Numéro de série parent » sur l'objet de nœud de stockage est renseigné de manière appropriée pour les baies Dell/EMC PowerStore lorsque les nœuds individuels se trouvent dans une appliance/boîtier intermédiaire qui fait uniquement partie d'un cluster plus grand.



== Configuration

|===


| Champ | Description 


 a| 
Passerelle(s) PowerStore
 a| 
Adresses IP ou noms de domaine complets du stockage PowerStore



 a| 
Nom d'utilisateur
 a| 
Nom d'utilisateur pour PowerStore



 a| 
Mot de passe
 a| 
Mot de passe utilisé pour PowerStore

|===


== Configuration avancée

|===


| Champ | Description 


 a| 
Port HTTPS
 a| 
La valeur par défaut est 443



 a| 
Intervalle d'interrogation des stocks (minutes)
 a| 
Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes.

|===
La collection de performances PowerStore de OnCommand Insight utilise les données sources de granularité de 5 minutes de PowerStore. C'est pourquoi Insight interroge ces données toutes les cinq minutes, ce qui n'est pas configurable.
