---
permalink: config-admin/e-series-landing-page-terminology-storage.html 
sidebar: sidebar 
keywords:  
summary: 'Termes s"appliquant aux objets ou aux références figurant sur les pages d"accueil des ressources de stockage NetApp E-Series.' 
---
= Système de stockage E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Termes s'appliquant aux objets ou aux références figurant sur les pages d'accueil des ressources de stockage NetApp E-Series.



== Terminologie du stockage E-Series

Les termes suivants s'appliquent aux objets ou références disponibles sur les pages d'accueil des ressources de stockage NetApp E-Series. Un grand nombre de ces termes s'appliquent également à d'autres collecteurs de données.

* Modèle -- nom du modèle du périphérique.
* Fournisseur -- même nom de fournisseur que vous pouvez voir si vous avez configuré une nouvelle source de données.
* Numéro de série -- le numéro de série de la matrice. Sur les systèmes de stockage d'architecture en cluster comme NetApp clustered Data ONTAP, ce numéro de série peut être moins utile que les numéros de série individuels des « nœuds de stockage ».
* IP -- est généralement le(s) IP(s) ou le(s) nom(s) d'hôte(s) configuré(s) dans la source de données.
* Version du microcode -- micrologiciel.
* Capacité brute -- somme de base 2 de tous les disques physiques du système, quel que soit leur rôle.
* Latence : représentation de l'hôte face aux workloads, en lecture et en écriture. Insight calcule une moyenne pondérée en IOPS à partir des volumes du stockage.
* Débit -- débit total face à l'hôte de la baie. Insight récapitule le débit des volumes pour dériver cette valeur.
* Gestion -- il peut contenir un lien hypertexte pour l'interface de gestion du périphérique. Créé par programmation par la source de données Insight dans le cadre du reporting d'inventaire.

