---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 'L"outil securityadmin vous permet de gérer les options de sécurité de l"utilisateur d"acquisition local \(LAU\). La gestion de la sécurité inclut la gestion des clés et des mots de passe, l"enregistrement et la restauration des configurations de sécurité que vous créez ou restaurez aux paramètres par défaut.' 
---
= Gestion de la sécurité sur l'unité d'acquisition locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `securityadmin` L'outil vous permet de gérer les options de sécurité de l'utilisateur d'acquisition local (LAU). La gestion de la sécurité inclut la gestion des clés et des mots de passe, l'enregistrement et la restauration des configurations de sécurité que vous créez ou restaurez aux paramètres par défaut.



== Avant de commencer

Vous devez avoir `admin` privilèges permettant d'effectuer des tâches de configuration de la sécurité.



== Description de la tâche

Vous utilisez le `securityadmin` outil de gestion de la sécurité :

* Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux : `/bin/oci-securityadmin.sh`


Pour plus d'informations, reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"]instructions.
