---
permalink: config-admin/managing-security-on-the-insight-server.html 
sidebar: sidebar 
keywords:  
summary: 'L"outil securityadmin vous permet de gérer les options de sécurité sur le serveur Insight. La gestion de la sécurité inclut la modification des mots de passe, la génération de nouvelles clés, l"enregistrement et la restauration des configurations de sécurité que vous créez ou la restauration des configurations par défaut.' 
---
= Gestion de la sécurité sur le serveur Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `securityadmin` Cet outil vous permet de gérer les options de sécurité sur le serveur Insight. La gestion de la sécurité inclut la modification des mots de passe, la génération de nouvelles clés, l'enregistrement et la restauration des configurations de sécurité que vous créez ou la restauration des configurations par défaut.



== Description de la tâche

Vous utilisez le `securityadmin` outil de gestion de la sécurité :

* Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux : `/bin/oci-securityadmin.sh`




== Étapes

. Effectuez une connexion à distance au serveur Insight.
. Démarrez l'outil d'administration de la sécurité en mode interactif :
+
** Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux : `/bin/oci-securityadmin.sh -i`
+
Le système demande des informations d'identification de connexion.



. Entrez le nom d'utilisateur et le mot de passe d'un compte avec les informations d'identification « Admin ».
. Sélectionnez *serveur*.
+
Les options de configuration de serveur suivantes sont disponibles :

+
** *Sauvegarde*
+
Crée un fichier zip de sauvegarde du coffre-fort contenant tous les mots de passe et clés et place le fichier à un emplacement spécifié par l'utilisateur ou aux emplacements par défaut suivants :

+
*** Vitres - `C:\Program Files\SANscreen\backup\vault`
*** Linux : `/var/log/netapp/oci/backup/vault`


** *Restaurer*
+
Restaure la sauvegarde zip du coffre-fort créé. Une fois restaurées, tous les mots de passe et clés sont rétablis dans les valeurs existantes au moment de la création de la sauvegarde.

+
[NOTE]
====
La restauration peut être utilisée pour synchroniser les mots de passe et les clés sur plusieurs serveurs, par exemple : - Modifier la clé de cryptage du serveur sur un serveur - Créer une sauvegarde du coffre-fort - Restaurer la sauvegarde du coffre-fort sur le second serveur

====
** *Changer la clé de cryptage*
+
Modifiez la clé de cryptage du serveur utilisée pour crypter ou décrypter les mots de passe des utilisateurs proxy, les mots de passe des utilisateurs SMTP, les mots de passe des utilisateurs LDAP, etc.

+
[NOTE]
====
Lorsque vous modifiez des clés de cryptage, vous devez sauvegarder votre nouvelle configuration de sécurité afin de pouvoir la restaurer après une mise à niveau ou une installation.

====
** *Mettre à jour le mot de passe*
+
Modifiez le mot de passe des comptes internes utilisés par Insight. Les options suivantes sont affichées :

+
*** _interne
*** acquisition
*** cognos_admin
*** dwh_interne
*** hôtes
*** inventaire
*** racine






[NOTE]
====
Certains comptes doivent être synchronisés lorsque les mots de passe sont modifiés. Par exemple, si vous modifiez le mot de passe de l'utilisateur 'acquisition' sur le serveur, vous devez modifier le mot de passe de l'utilisateur 'acquisition' sur LAU, RAU et DWH pour qu'il corresponde. De même, lorsque vous modifiez des mots de passe, vous devez sauvegarder votre nouvelle configuration de sécurité afin de pouvoir la restaurer après une mise à niveau ou une installation.

====
* *Rétablir les valeurs par défaut*
+
Réinitialise les clés et les mots de passe aux valeurs par défaut. Les valeurs par défaut sont celles fournies lors de l'installation.

* *Quitter*
+
Quittez le `securityadmin` outil.

+
.. Choisissez l'option que vous souhaitez modifier et suivez les invites.



