---
permalink: config-admin/managing-security-on-the-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 'L"outil securityadmin vous permet de gérer les options de sécurité sur le serveur Data Warehouse. La gestion de la sécurité inclut la mise à jour des mots de passe internes des utilisateurs internes sur le serveur DWH, la création de sauvegardes de la configuration de sécurité ou la restauration des configurations par défaut.' 
---
= Gestion de la sécurité dans l'entrepôt de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `securityadmin` L'outil vous permet de gérer les options de sécurité sur le serveur Data Warehouse. La gestion de la sécurité inclut la mise à jour des mots de passe internes des utilisateurs internes sur le serveur DWH, la création de sauvegardes de la configuration de sécurité ou la restauration des configurations par défaut.



== Description de la tâche

Vous utilisez le `securityadmin` outil de gestion de la sécurité :

* Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux : `/bin/oci-securityadmin.sh`




== Étapes

. Effectuez une connexion à distance au serveur Data Warehouse.
. Démarrez l'outil d'administration de la sécurité en mode interactif : `Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i``Linux - /bin/oci-securityadmin.sh -i`
+
Le système demande des informations d'identification de connexion.

. Entrez le nom d'utilisateur et le mot de passe d'un compte avec les informations d'identification « Admin ».
+
Le système affiche le menu d'administration de la sécurité pour l'entrepôt de données :

+
** *Sauvegarde*
+
Crée un fichier zip de sauvegarde du coffre-fort contenant tous les mots de passe et clés et place le fichier à un emplacement spécifié par l'utilisateur ou à l'emplacement par défaut :

+
*** Vitres - `C:\Program Files\SANscreen\backup\vault`
*** Linux : `/var/log/netapp/oci/backup/vault`


** *Restaurer*
+
Restaure la sauvegarde zip du coffre-fort créé. Une fois restaurées, tous les mots de passe et clés sont rétablis dans les valeurs existantes au moment de la création de la sauvegarde.

+
[NOTE]
====
La restauration peut être utilisée pour synchroniser les mots de passe et les clés sur plusieurs serveurs, par exemple : - Modifier les clés de cryptage sur un serveur - Créer une sauvegarde du coffre-fort - Restaurer la sauvegarde du coffre-fort sur le second serveur

+

====
** *Changer les clés de cryptage*
+
Modifiez la clé de cryptage DWH utilisée pour crypter ou décrypter des mots de passe tels que les mots de passe de connecteur et les mots de passe SMPT.

** *Mettre à jour le mot de passe*
+
Modifier le mot de passe d'un compte utilisateur spécifique.

+
*** _interne
*** acquisition
*** cognos_admin
*** dwh
*** dwh_interne
*** dwhuser
*** hôtes
*** inventaire
*** racine




+
[NOTE]
====
Lorsque vous modifiez les mots de passe dwhuser, hosts, Inventory ou root, vous avez la possibilité d'utiliser le hachage de mot de passe SHA-256. Cette option nécessite que tous les clients accédant aux comptes utilisent des connexions SSL.

====
+
** *Rétablir les valeurs par défaut*
+
Réinitialise les clés de cryptage et les mots de passe aux valeurs par défaut. Les valeurs par défaut sont celles fournies lors de l'installation.

** *Quitter*
+
Quittez le `securityadmin` outil.




