---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 'L"outil securityadmin vous permet de gérer les options de sécurité de l"utilisateur d"acquisition local \(LAU\). La gestion de la sécurité inclut la gestion des clés et des mots de passe, l"enregistrement et la restauration des configurations de sécurité que vous créez ou restaurez aux paramètres par défaut.' 
---
= Gestion de la sécurité sur l'unité d'acquisition locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `securityadmin` L'outil vous permet de gérer les options de sécurité de l'utilisateur d'acquisition local (LAU). La gestion de la sécurité inclut la gestion des clés et des mots de passe, l'enregistrement et la restauration des configurations de sécurité que vous créez ou restaurez aux paramètres par défaut.



== Avant de commencer

Vous devez avoir `admin` privilèges permettant d'effectuer des tâches de configuration de la sécurité.



== Description de la tâche

Vous utilisez le `securityadmin` outil de gestion de la sécurité :

* Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux : `/bin/oci-securityadmin.sh`




== Étapes

. Effectuez une connexion à distance au serveur Insight.
. Démarrez l'outil d'administration de la sécurité en mode interactif :
+
** Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux : `/bin/oci-securityadmin.sh -i`
+
Le système demande des informations d'identification de connexion.



. Entrez le nom d'utilisateur et le mot de passe d'un compte avec les informations d'identification « Admin ».
. Sélectionnez *unité d'acquisition locale* pour reconfigurer la configuration de sécurité de l'unité d'acquisition locale.
+
Les options suivantes sont affichées :

+
** *Sauvegarde*
+
Crée un fichier zip de sauvegarde du coffre-fort contenant tous les mots de passe et clés et place le fichier à un emplacement spécifié par l'utilisateur ou aux emplacements par défaut suivants :

+
*** Vitres - `C:\Program Files\SANscreen\backup\vault`
*** Linux : `/var/log/netapp/oci/backup/vault`


** *Restaurer*
+
Restaure la sauvegarde zip du coffre-fort créé. Une fois restaurées, tous les mots de passe et clés sont rétablis dans les valeurs existantes au moment de la création de la sauvegarde.

+
[NOTE]
====
Restore peut être utilisé pour synchroniser les mots de passe et les clés sur plusieurs serveurs, par exemple : - Modifier les clés de cryptage sur LE LAU - Créer une sauvegarde du coffre-fort - Restaurer la sauvegarde du coffre-fort sur chacun des Raus

====
** *Changer les clés de cryptage*
+
Modifiez les clés de cryptage au utilisées pour crypter ou décrypter les mots de passe des périphériques.

+
[NOTE]
====
Lorsque vous modifiez des clés de cryptage, vous devez sauvegarder votre nouvelle configuration de sécurité afin de pouvoir la restaurer après une mise à niveau ou une installation.

====
** *Mettre à jour le mot de passe*
+
Modifier le mot de passe du compte utilisateur « acquisition ».

+
[NOTE]
====
Certains comptes doivent être synchronisés lorsque les mots de passe sont modifiés. Par exemple, si vous modifiez le mot de passe de l'utilisateur 'acquisition' sur le serveur, vous devez modifier le mot de passe de l'utilisateur 'acquisition' sur LAU, RAU et DWH pour qu'il corresponde. De même, lorsque vous modifiez des mots de passe, vous devez sauvegarder votre nouvelle configuration de sécurité afin de pouvoir la restaurer après une mise à niveau ou une installation.

====
** *Rétablir les valeurs par défaut*
+
Réinitialise le mot de passe de l'utilisateur d'acquisition et les clés de cryptage de l'utilisateur d'acquisition sur les valeurs par défaut. Les valeurs par défaut sont celles fournies lors de l'installation.

** *Quitter*
+
Quittez le `securityadmin` outil.



. Choisissez l'option que vous souhaitez configurer et suivez les invites.

