---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: 'L"outil securityadmin vous permet de gérer les options de sécurité sur Raus. Vous devrez peut-être sauvegarder ou restaurer une configuration de coffre-fort, modifier les clés de cryptage ou mettre à jour les mots de passe des unités d"acquisition.' 
---
= Gestion de la sécurité sur un RAU
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `securityadmin` L'outil vous permet de gérer les options de sécurité sur Raus. Vous devrez peut-être sauvegarder ou restaurer une configuration de coffre-fort, modifier les clés de cryptage ou mettre à jour les mots de passe des unités d'acquisition.



== Description de la tâche

Vous utilisez le `securityadmin` outil de gestion de la sécurité :

* Vitres - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux : `/bin/oci-securityadmin.sh`


Un scénario de mise à jour de la configuration de sécurité pour le LAU/RAU consiste à mettre à jour le mot de passe utilisateur d'acquisition lorsque le mot de passe de cet utilisateur a été modifié sur le serveur. Le LAU et tous les Raus utilisent le même mot de passe que celui de l'utilisateur d'acquisition du serveur pour communiquer avec le serveur.

L'utilisateur 'acquisition' n'existe que sur le serveur Insight. Le RAU ou LAU se connecte en tant qu'utilisateur lorsqu'il se connecte au serveur.

Pour plus d'informations, reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"]instructions.
