---
permalink: config-admin/using-options-in-the-preferences-tab.html 
sidebar: sidebar 
keywords:  
summary: 'L"onglet Préférences de résolution du périphérique permet de créer un programme de résolution automatique, de spécifier des venders de stockage et de bande à inclure ou exclure de l"identification, et de définir des options de recherche DNS.' 
---
= Configuration des options dans l'onglet Préférences
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'onglet Préférences de résolution du périphérique permet de créer un programme de résolution automatique, de spécifier des venders de stockage et de bande à inclure ou exclure de l'identification, et de définir des options de recherche DNS.



== Planning de résolution automatique

Un planning de résolution automatique peut indiquer quand la résolution automatique du périphérique est exécutée :

|===


| Option | Description 


 a| 
Toutes les
 a| 
Utilisez cette option pour exécuter la résolution automatique des périphériques aux intervalles de jours, heures ou minutes.



 a| 
Tous les jours
 a| 
Utilisez cette option pour exécuter la résolution automatique du périphérique tous les jours à une heure donnée.



 a| 
Manuellement
 a| 
Utilisez cette option pour exécuter uniquement la résolution automatique des périphériques manuellement.



 a| 
Sur chaque changement d'environnement
 a| 
Utilisez cette option pour exécuter la résolution automatique des périphériques lorsqu'un changement d'environnement est apporté.

|===
Si vous spécifiez manuellement, la résolution automatique du périphérique de nuit est désactivée.



== Options de traitement DNS

Les options de traitement DNS vous permettent de sélectionner les fonctions suivantes :

* Lorsque le traitement des résultats de recherche DNS est activé, vous pouvez ajouter une liste de noms DNS à ajouter aux périphériques résolus.
* Vous pouvez sélectionner « résolution automatique des adresses IP : » pour activer la résolution automatique des hôtes pour les initiateurs iSCSI et les hôtes accédant aux partages NFS à l'aide de la recherche DNS. Si ce n'est pas spécifié, seule la résolution FC est effectuée.
* Vous pouvez choisir d'autoriser des traits de soulignement dans les noms d'hôte et d'utiliser un alias « connecté à » au lieu de l'alias de port standard dans les résultats.




== Y compris les fournisseurs spécifiques de systèmes de stockage et de bandes, ou l'exclusion de ces fournisseurs

Vous pouvez inclure ou exclure certains fournisseurs de stockage et de bandes pour la résolution automatique. Vous pouvez exclure des fournisseurs spécifiques si vous savez, par exemple, qu'un hôte spécifique deviendra un hôte hérité et qu'il doit être exclu de votre nouvel environnement. Vous pouvez également réajouter des fournisseurs que vous avez précédemment exclus mais qui ne souhaitez plus exclure.

[NOTE]
====
Les règles de résolution des périphériques pour les bandes ne fonctionnent que pour les WWN où le fournisseur de ce WWN est défini sur *inclus comme bande uniquement* dans les préférences des fournisseurs.

====