---
permalink: install-windows/installing-data-source-patches.html 
sidebar: sidebar 
keywords:  
summary: 'Le cas échéant, vous devez installer les derniers correctifs disponibles pour vos sources de données pour profiter des dernières fonctionnalités et améliorations. Après avoir téléchargé un correctif de source de données, vous pouvez l"installer sur toutes les sources de données du même type.' 
---
= Installation des correctifs de source de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le cas échéant, vous devez installer les derniers correctifs disponibles pour vos sources de données pour profiter des dernières fonctionnalités et améliorations. Après avoir téléchargé un correctif de source de données, vous pouvez l'installer sur toutes les sources de données du même type.



== Avant de commencer

Vous devez avoir contacté le support technique et obtenu le `.zip` fichier contenant les derniers correctifs de source de données en leur fournissant la version à partir de laquelle vous effectuez la mise à niveau et la version vers laquelle vous souhaitez effectuer la mise à niveau.



== Étapes

. Placez le fichier correctif sur le serveur Insight.
. Dans la barre d'outils Insight, cliquez sur *Admin*.
. Cliquez sur *Patches*.
. Dans le bouton actions, sélectionnez *appliquer patch*.
. Dans la boîte de dialogue *Apply data source patch*, cliquez sur *Browse* pour localiser le fichier correctif téléchargé.
. Examinez les types de sources de données *Patch name*, *Description* et *impactées*.
. Si le correctif sélectionné est correct, cliquez sur *appliquer le correctif*.
+
Toutes les sources de données du même type sont mises à jour avec ce correctif. Insight force automatiquement l'acquisition à redémarrer lorsque vous ajoutez une source de données. La découverte inclut la détection des modifications de la topologie réseau, notamment l'ajout ou la suppression de nœuds ou d'interfaces.

. Pour forcer manuellement le processus de découverte, cliquez sur *sources de données* et cliquez sur *interroger à nouveau* en regard de la source de données pour forcer la collecte immédiate des données.
+
Si la source de données est déjà dans un processus d'acquisition, Insight ignore la requête d'interrogation à nouveau.


