---
permalink: install-windows/installing-the-anomaly-detection-software.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight contient le logiciel qui applique la détection d"anomalies du machine learning à vos données Insight. Vous pouvez installer ce logiciel séparément des autres composants OnCommand Insight.' 
---
= Installation du logiciel de détection des anomalies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight contient le logiciel qui applique la détection d'anomalies du machine learning à vos données Insight. Vous pouvez installer ce logiciel séparément des autres composants OnCommand Insight.



== Avant de commencer

Vous devez avoir terminé toutes les conditions préalables à l'installation.



== Étapes

. Connectez-vous au serveur de détection des anomalies à l'aide d'un compte avec privilèges sudo.
. Copiez le `.zip` Fichier contenant le logiciel de détection des anomalies sur le serveur Linux.
. Extrayez les fichiers dans le `oci-prelert-<version>-linux-x86_64` répertoire.
. Accédez au répertoire dans lequel se trouve le programme d'installation : `cd oci-prelert-<version>-linux-x86_64`
. Installez le logiciel de détection des anomalies : `sudo ./oci-prelert-install.sh`
+
Pendant l'installation, vous êtes invité à entrer le nom du serveur ou l'adresse IP du serveur OnCommand Insight, ainsi que le nom d'utilisateur et le mot de passe d'un compte disposant de privilèges d'administrateur.

+
Pour supprimer le logiciel de détection des anomalies, utilisez la commande suivante : `sudo /usr/bin/oci-prelert-uninstall.sh`





== Résultats

Le logiciel est automatiquement enregistré avec l'instance de OnCommand Insight spécifiée dans l'installation. Le logiciel ne peut communiquer qu'avec l'instance OnCommand Insight avec laquelle il est enregistré et une seule instance du logiciel peut être enregistrée auprès d'un serveur OnCommand Insight.

Si vous redémarrez le serveur qui exécute le logiciel de détection des anomalies ou le serveur Insight, le processus de détection des anomalies redémarre automatiquement.

[NOTE]
====
Si vous installez le logiciel de détection des anomalies via la ligne de commande en fournissant des paramètres, au lieu de laisser l'invite d'installation vous indiquer les paramètres, l'enregistrement échoue avec le serveur Insight, sauf si vous fournissez le paramètre suivant : `--path rest/v1`

====