---
permalink: install-windows/remote-acquisition-unit-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 'Vous devez installer une unité d"acquisition à distance \(RAU\) pour acquérir des informations à partir de périphériques SAN situés derrière un pare-feu, sur un site distant, sur un réseau privé ou dans des segments de réseau différents. Avant d"installer le RAU, assurez-vous que votre environnement est conforme aux exigences du système d"exploitation RAU, du processeur, de la mémoire et de l"espace disque.' 
---
= Configuration requise pour le serveur de l'unité d'acquisition à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer une unité d'acquisition à distance (RAU) pour acquérir des informations à partir de périphériques SAN situés derrière un pare-feu, sur un site distant, sur un réseau privé ou dans différents segments de réseau. Avant d'installer le RAU, assurez-vous que votre environnement est conforme aux exigences du système d'exploitation RAU, du processeur, de la mémoire et de l'espace disque.

|===


| Composant | Conditions requises 


 a| 
Système d'exploitation
 a| 
Un ordinateur exécutant Microsoft Windows Server 2012, 2012 R2, 2016 ou 2019 64 bits avec le dernier Service Pack



 a| 
CPU
 a| 
4 cœurs de processeurs



 a| 
Mémoire
 a| 
16 GO DE RAM



 a| 
Espace disque disponible
 a| 
40 GO



 a| 
Le réseau
 a| 
Connexion Ethernet 100 Mbit/s /1 Gbit/s, adresse IP statique, connectivité IP à tous les périphériques FC et port requis au serveur OnCommand Insight (80 ou 443).



 a| 
Autorisations
 a| 
Autorisations d'administrateur local sur le serveur RAU



 a| 
Analyse antivirus
 a| 
Pendant l'installation de ce composant OnCommand Insight, vous devez désactiver complètement tous les antivirus. Après l'installation, les chemins utilisés par le composant Insight doivent être exclus de l'analyse antivirus. En outre, vous devez également exclure le dossier IBM/DB2 (par exemple _C:\Program Files\IBM\DB2_) de l'analyse antivirus après l'installation.

|===