---
permalink: install-windows/uninstalling-the-remote-acquisition-unit-software.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez désinstaller la version existante du logiciel de l"unité d"acquisition distante avant de pouvoir mettre à niveau vers une nouvelle version. Vous devez effectuer cette tâche sur tous les serveurs d"unités d"acquisition distants de votre environnement.' 
---
= Désinstallation du logiciel de l'unité d'acquisition distante
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez désinstaller la version existante du logiciel de l'unité d'acquisition distante avant de pouvoir mettre à niveau vers une nouvelle version. Vous devez effectuer cette tâche sur tous les serveurs d'unités d'acquisition distants de votre environnement.

[NOTE]
====
*Il est fortement recommandé de sauvegarder le coffre-fort* avant de désinstaller OnCommand Insight. *Vous devez sauvegarder le coffre-fort* si vous allez mettre à niveau OnCommand Insight.

Pour plus d'informations, reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"]instructions.

====


== Étapes

. Connectez-vous au serveur de l'unité d'acquisition distante.
. Vérifiez que toutes les fenêtres OnCommand Insight du serveur sont fermées.
. Ouvrez la fonction *Désinstaller un programme* à partir du panneau de commande et sélectionnez le programme unité d'acquisition à distance OnCommand Insight à supprimer.
. Cliquez sur *Désinstaller* et suivez les invites.

