---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 'Une fois toutes les tâches préalables terminées, vous pouvez vous connecter au serveur Data Warehouse et exécuter le package d"installation pour terminer la mise à niveau.' 
---
= Mise à niveau de Data Warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois toutes les tâches préalables terminées, vous pouvez vous connecter au serveur Data Warehouse et exécuter le package d'installation pour terminer la mise à niveau.



== Description de la tâche

La mise à niveau en ligne n'est pas prise en charge par l'entrepôt de données (DWH). Procédez comme suit pour effectuer une mise à niveau vers la nouvelle version du logiciel DWH.

[NOTE]
====
*Vous devez sauvegarder le coffre-fort* avant de mettre à niveau DWH.

Pour plus d'informations, reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"]instructions.

====


== Étapes

Lors de la mise à niveau de l'entrepôt de données, vous devez effectuer les actions suivantes :

. Après avoir installé DWH 7.3.16, restaurez le coffre-fort et la base de données dans l'ordre suivant :
+
.. Coffre-fort
.. Base de données


. Connectez-vous au serveur DWH à l'aide d'un compte disposant des autorisations d'administrateur local Windows.
. Sauvegardez la base de données DWH et les rapports à l'aide de l'interface du portail DWH.
. Sauvegardez le coffre-fort. Voir la link:../config-admin/security-management.html["Admin sécurité"] documentation.
. Désinstallez le logiciel DWH du serveur.
. Redémarrez le serveur pour supprimer des composants de la mémoire.
. Installez la nouvelle version de DWH sur le serveur.
+
L'installation dure environ 2 heures. Il est recommandé de laisser toutes les valeurs par défaut sélectionnées.

. Restaurez le coffre-fort sur le serveur DWH.
. Restaurez la base de données DWH sur le serveur.




== Une fois que vous avez terminé

Après la mise à niveau, vous devez restaurer la base de données Data Warehouse, qui peut prendre autant de temps ou plus longtemps que la mise à niveau.

[NOTE]
====
Lors d'une mise à niveau de OnCommand Insight, il n'est pas rare qu'un client passe à un autre serveur Insight. Si vous avez modifié votre serveur Insight, après avoir restauré la base de données de l'entrepôt de données, les connecteurs existants pointent vers l'adresse IP ou le nom d'hôte du serveur précédent. Il est recommandé de supprimer le connecteur et d'en créer un nouveau afin d'éviter d'éventuelles erreurs.

====