---
permalink: install-windows/upgrading-insight.html 
sidebar: sidebar 
keywords:  
summary: 'Une fois toutes les tâches préalables terminées, vous vous connectez au serveur Insight et exécutez le package d"installation pour terminer la mise à niveau. Le processus de mise à niveau désinstalle le logiciel existant, installe le nouveau logiciel, puis redémarre le serveur.' 
---
= Mise à niveau d'Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois toutes les tâches préalables terminées, vous vous connectez au serveur Insight et exécutez le package d'installation pour terminer la mise à niveau. Le processus de mise à niveau désinstalle le logiciel existant, installe le nouveau logiciel, puis redémarre le serveur.



== Avant de commencer

Le package d'installation d'Insight doit être situé sur le serveur.

[NOTE]
====
*Vous devez sauvegarder le coffre-fort* avant de mettre à niveau OnCommand Insight.

Pour plus d'informations, reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"]instructions.

====


== Étapes

. Connectez-vous au serveur Insight à l'aide d'un compte disposant des autorisations d'administrateur local Windows.
. Recherchez le pack d'installation d'Insight (`SANscreenServer-x64-version_number-build_number.msi`) À l'aide de l'Explorateur Windows et double-cliquez dessus.
+
L'assistant de configuration de OnCommand s'affiche.

. Éloignez la fenêtre de progression du centre de l'écran et de la fenêtre de l'assistant *Setup* de sorte que les erreurs générées ne soient pas masquées.
. Suivez les invites de l'assistant d'installation.
+
Il est recommandé de laisser toutes les valeurs par défaut sélectionnées.





== Une fois que vous avez terminé

Pour vérifier si la mise à niveau a réussi ou si des erreurs sont générées, consultez le journal de mise à niveau à l'emplacement suivant : `<install directory>\SANscreen\wildfly\standalone\log`.
