---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 'Une fois toutes les tâches préalables terminées, vous pouvez vous connecter au serveur Data Warehouse et exécuter le package d"installation pour terminer la mise à niveau.' 
---
= Mise à niveau de Data Warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois toutes les tâches préalables terminées, vous pouvez vous connecter au serveur Data Warehouse et exécuter le package d'installation pour terminer la mise à niveau.



== Description de la tâche

La mise à niveau en ligne n'est pas prise en charge par l'entrepôt de données (DWH). Procédez comme suit pour effectuer une mise à niveau vers la nouvelle version du logiciel DWH.

[NOTE]
====
Lors de la mise à niveau de DWH, le dossier contenant la sauvegarde du coffre-fort _securityadmin_ Tool est supprimé. Il est fortement recommandé de sauvegarder le coffre-fort avant de mettre à niveau DWH. Pour référence, les dossiers de coffre-fort par défaut sont les suivants :

* Dossier du coffre-fort (coffres-forts en cours d'utilisation):``%SANSCREEN_HOME%\wildfly\standalone\configuration\vault``
* Sauvegardes de coffre-fort : `%SANSCREEN_HOME%\backup\vault`


Voir http://ie-docs.rtp.openeng.netapp.com/oci-73_ram/topic/com.netapp.doc.oci-acg/GUID-E3351676-2088-4767-AAB5-CB1D8476291C.html?resultof=%22%76%61%75%6c%74%22%20["Gestion de la sécurité dans l'entrepôt de données"] pour en savoir plus.

====


== Étapes

. Connectez-vous au serveur DWH à l'aide d'un compte disposant des autorisations d'administrateur local Windows.
. Sauvegardez la base de données DWH et les rapports à l'aide de l'interface du portail DWH.
. Sauvegardez la configuration de sécurité si le serveur utilise une configuration de sécurité autre que celle par défaut.
. Désinstallez le logiciel DWH du serveur.
. Redémarrez le serveur pour supprimer des composants de la mémoire.
. Installez la nouvelle version de DWH sur le serveur.
+
L'installation dure environ 2 heures. Il est recommandé de laisser toutes les valeurs par défaut sélectionnées.

. Restaurez la configuration de sécurité non par défaut sur le serveur DWH.
. Restaurez la base de données DWH sur le serveur.




== Une fois que vous avez terminé

Après la mise à niveau, vous devez restaurer la base de données Data Warehouse, qui peut prendre autant de temps ou plus longtemps que la mise à niveau.

[NOTE]
====
Lors d'une mise à niveau de OnCommand Insight, il n'est pas rare qu'un client passe à un autre serveur Insight. Si vous avez modifié votre serveur Insight, après avoir restauré la base de données de l'entrepôt de données, les connecteurs existants pointent vers l'adresse IP ou le nom d'hôte du serveur précédent. Il est recommandé de supprimer le connecteur et d'en créer un nouveau afin d'éviter d'éventuelles erreurs.

====