---
permalink: install-windows/upgrading-the-anomaly-detection-engine.html 
sidebar: sidebar 
keywords:  
summary: 'À partir de OnCommand Insight version 7.3.9, vous pouvez effectuer une mise à niveau à la volée du logiciel de détection des anomalies. La mise à niveau à la volée préserve les données de détection des anomalies et les scores d"anomalies.' 
---
= Mise à niveau du moteur de détection des anomalies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de OnCommand Insight version 7.3.9, vous pouvez effectuer une mise à niveau à la volée du logiciel de détection des anomalies. La mise à niveau à la volée préserve les données de détection des anomalies et les scores d'anomalies.



== Avant de commencer

* Le système doit exécuter OnCommand Insight 7.3.7 ou une version ultérieure.
* Il est recommandé de mettre à niveau le serveur OnCommand Insight avant de mettre à niveau le moteur de détection des anomalies.




== Description de la tâche

Procédez comme suit pour effectuer la mise à niveau :



== Étapes

. Accédez au répertoire dans lequel se trouve le programme d'installation : `cd oci-prelert-<version>-linux-x86_64`
. Installez le logiciel de mise à niveau de la détection des anomalies : `sudo ./oci-prelert-install.sh`
+
Le logiciel de détection des anomalies est correctement enregistré sur le serveur OnCommand Insight.


