---
permalink: install-linux/insight-java-ui-requirements.html 
sidebar: sidebar 
keywords:  
summary: 'Étant donné que le client d"interface utilisateur OnCommand Insight Java fonctionne dans un environnement d"exécution Java sur votre ordinateur, il est important de s"assurer que votre environnement répond à des exigences spécifiques en matière de système d"exploitation, de processeur et de mémoire.' 
---
= Configuration requise pour l'interface utilisateur Java Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Étant donné que le client d'interface utilisateur OnCommand Insight Java fonctionne dans un environnement d'exécution Java sur votre ordinateur, il est important de s'assurer que votre environnement répond à des exigences spécifiques en matière de système d'exploitation, de processeur et de mémoire.

Pour accéder au client Java UI, vous devez installer l'environnement d'exécution Java (JRE) sur votre ordinateur.

Pour OnCommand Insight 7.3.2 et versions ultérieures, la version 64 bits de l'environnement d'exécution Java (JRE) est nécessaire pour exécuter le client Insight Java.

|===


| Composant | Conditions requises 


 a| 
Système d'exploitation
 a| 
Toute machine compatible Java 8. Le client Java prend en charge les plates-formes Windows, Macintosh et Linux.



 a| 
CPU
 a| 
1.8 GHz ou plus rapide est requis.



 a| 
Mémoire
 a| 
2 Go ou plus sont recommandés. Si vous surveillez les performances des centres de données complexes (plus de 50,000 ports de commutation), le serveur requiert plus de mémoire. Ceci est applicable uniquement si la licence Perform est installée.

|===