---
permalink: install-linux/installing-the-oncommand-insight-server-linux.html 
sidebar: sidebar 
keywords:  
summary: 'Le serveur OnCommand Insight est installé à l"aide de la ligne de commande.' 
---
= Installation du serveur OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le serveur OnCommand Insight est installé à l'aide de la ligne de commande.



== Avant de commencer

Vous devez avoir terminé toutes les conditions préalables à l'installation.



== Étapes

. Connectez-vous au serveur Insight à l'aide d'un compte avec des privilèges sudo.
. Accédez au répertoire du serveur où se trouvent les fichiers d'installation et saisissez la commande suivante :
+
`unzip oci-<version>-linux-x86_64.zip`

+
Vérifiez le numéro de version du fichier d'installation ; le numéro de version peut être différent de celui indiqué dans la commande.

. Vous pouvez afficher la syntaxe, les arguments de commande et l'utilisation des paramètres pour `oci-install.sh` :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --help`

. Exécutez le script d'installation :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh`

+
Lors de l'installation d'Insight Server sur CentOS 9 Stream, Red Hat Enterprise Linux 9.4 ou Oracle Linux 9.4, vous devez d'abord passer au répertoire contenant le fichier d'installation, puis exécuter la commande install à l'aide de l'option de ligne de commande "--install-mysql-dépendances" :

+
....
cd /tmp/oci-7.3.16.1.297-linux-x86_64
sudo ./oci-install.sh --install-mysql-dependencies
....
. Lisez le contrat de licence, acceptez-le et suivez les invites.
. Si vous utilisez le modèle de licence Insight Consumption, vous devez activer l'envoi des informations d'utilisation à NetApp. Entrez `Y` à cette invite.




== Résultats

Après avoir répondu à toutes les invites, l'installation commence et devrait prendre environ 10 minutes, selon les applications installées.

. Si vous installez une unité d'acquisition à distance (RAU), vous devez exécuter l'outil SecurityAdmin pour créer un mot de passe pour l'utilisateur _acquisition_. Vous aurez besoin de ce mot de passe lors de l'installation du RAU.
+
Remarque : si vous avez créé ce mot de passe, vous devez _ne_ pas_ synchroniser le serveur et RAU comme indiqué ci-dessous.





== Synchroniser le serveur avec DWH et RAU


IMPORTANT: Après avoir installé l'unité d'acquisition distante et/ou l'entrepôt de données, vous devez *synchroniser* l'unité RAU/DWH avec le serveur OnCommand Insight. Suivez les étapes indiquées ci-dessous :

link:../install-windows/installing-a-remote-acquisition-unit-rau.html#synchronize-server-and-rau["Synchroniser Server et RAU (Windows)"]

link:../install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html#synchronize-server-and-dwh["Synchroniser Server et DWH (Windows)"]

link:../install-linux/installing-a-remote-acquisition-unit-rau-linux.html#synchronize-server-and-rau["Synchroniser Server et RAU (Linux)"]

link:../install-linux/installing-oncommand-insight-data-warehouse-linux.html#synchronize-server-and-dwh["Synchroniser Server et DWH (Linux)"]
