---
permalink: install-linux/oncommand-insight-installation-instructions.html 
sidebar: sidebar 
keywords:  
summary: 'L"installation nécessite l"installation de plusieurs composants OnCommand Insight, d"Insight Server, d"entrepôt de données et de détection d"anomalie.' 
---
= Instructions d'installation de Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installation nécessite l'installation de plusieurs composants OnCommand Insight, d'Insight Server, d'entrepôt de données et de détection d'anomalie.

L'installation comprend les tâches principales suivantes :

* Téléchargement du programme d'installation de OnCommand Insight
* Installation du serveur OnCommand Insight
* Installation des licences
* Vous pouvez également installer DWH et Reporting (doit être installé sur une machine ou une machine virtuelle distincte). La création de rapports nécessite Microsoft Windows.)
* En option, l'installation d'une unité d'acquisition à distance (RAU), qui acquiert des informations à partir des ressources de votre périphérique qui résident derrière un pare-feu, se trouve sur un site distant ou se trouve sur un réseau privé
* Installation facultative du moteur de détection des anomalies (doit être installé sur une machine ou une machine virtuelle distincte).


Après l'installation, vous devez configurer Insight pour acquérir des informations sur votre environnement. Les tâches requises sont décrites dans le _Guide de configuration et d'administration de OnCommand Insight_.
