---
permalink: install-linux/submitting-an-online-technical-support-request.html 
sidebar: sidebar 
keywords:  
summary: 'En cas de problème avec l"installation d"Insight, en tant que client de support enregistré, vous pouvez envoyer une demande de support technique en ligne.' 
---
= Soumission d'une demande d'assistance technique en ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cas de problème avec l'installation d'Insight, en tant que client de support enregistré, vous pouvez envoyer une demande de support technique en ligne.



== Avant de commencer

À l'aide de votre adresse e-mail d'entreprise, vous devez vous inscrire en tant que client d'assistance pour obtenir des services d'assistance en ligne. L'enregistrement s'effectue via le site du support .



== Description de la tâche

Pour aider le support client à résoudre le problème d'installation, vous devez recueillir autant d'informations que possible, y compris les éléments suivants :

* Numéro de série de l'Insight
* Description du problème
* Tous les fichiers journaux Insight
* Capture d'écran de tous les messages d'erreur




== Étapes

. Créer un `.zip` fichier des informations recueillies pour créer un package de dépannage.
. Connectez-vous au site du support à l'adresse http://mysupport.netapp.com/["mysupport.netapp.com"] Et sélectionnez *assistance technique*.
. Cliquez sur *Ouvrir un cas*.
. Suivez les instructions de votre paquet de données.




== Une fois que vous avez terminé

Vous pouvez utiliser *vérifier l'état du dossier* sur la page assistance technique pour suivre votre demande.
