---
permalink: install-linux/uninstalling-an-ethernet-monitoring-unit-emu-linux.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez désinstaller une unité de surveillance Ethernet lorsque vous n"en avez plus besoin.' 
---
= Désinstallation d'une unité de surveillance Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez désinstaller une unité de surveillance Ethernet lorsque vous n'en avez plus besoin.



== Description de la tâche

[NOTE]
====
L'unité de surveillance Ethernet (EMU) n'est pas prise en charge dans OnCommand Insight version 7.3.12 et ultérieure.

====


== Étapes

. Connectez-vous au serveur de l'unité de surveillance Ethernet à l'aide d'un compte avec des privilèges sudo.
. Assurez-vous que toutes les fenêtres OnCommand Insight sont fermées.
. Vous pouvez afficher la syntaxe, les arguments de commande et l'utilisation des paramètres pour `uninstall.sh` en saisissant la commande suivante : `sudo /usr/bin/oci-uninstall.sh --help`
. Tapez la commande suivante : `sudo /usr/bin/oci-uninstall.sh`
+
Le script de désinstallation s'exécute. Suivez les invites.

. Une fois la désinstallation terminée, redémarrez le serveur.

