---
permalink: install-linux/uninstalling-a-remote-acquisition-unit-rau.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez désinstaller une unité d"acquisition à distance lorsque vous n"en avez plus besoin.' 
---
= Désinstallation d'une unité d'acquisition à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez désinstaller une unité d'acquisition à distance lorsque vous n'en avez plus besoin.

[NOTE]
====
*Il est fortement recommandé de sauvegarder le coffre-fort* avant de désinstaller OnCommand Insight.

Pour plus d'informations, reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"]instructions.

====


== Étapes

. Connectez-vous au serveur Remote acquisition Unit à l'aide d'un compte avec privilèges sudo.
. Assurez-vous que toutes les fenêtres OnCommand Insight sont fermées.
. Vous pouvez afficher la syntaxe, les arguments de commande et l'utilisation des paramètres pour `uninstall.sh` en saisissant la commande suivante : `sudo /usr/bin/oci-uninstall.sh --help`
. Tapez la commande suivante : `sudo /usr/bin/oci-uninstall.sh`
+
Le script de désinstallation s'exécute. Suivez les invites.


