---
permalink: install-linux/upgrading-insight-server-software.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez vérifier les mises à jour du serveur OnCommand Insight après vous être connecté au serveur. 
---
= Mise à niveau du logiciel Insight Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez vérifier les mises à jour du serveur OnCommand Insight après vous être connecté au serveur.

[NOTE]
====
Il est fortement recommandé de sauvegarder le coffre-fort et la base de données avant de mettre OnCommand Insight à niveau.

Reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"] instructions pour plus d'informations sur le coffre-fort.

====


== Étapes

. Dans la barre d'outils Insight, cliquez sur l'icône *aide*.
. Sélectionnez *Rechercher les mises à jour*.
. Cliquez sur *OK* si le `Version is up to date` s'affiche.
. Si une version plus récente est détectée, cliquez sur le lien *télécharger ici* dans la boîte de message.
. Sur la page *Download*, cliquez sur *download*. Notez l'emplacement du répertoire de téléchargement.
+
Vous pouvez également télécharger la nouvelle version sur le site de support NetApp.

. Connectez-vous au serveur Insight à l'aide d'un compte avec des privilèges sudo.
. Accédez au répertoire de téléchargement et tapez la commande suivante :
+
`unzip oci-<version>-linux-x86_64.zip`

+
Vérifiez que vous disposez du numéro de version correct du fichier d'installation.

. Vous pouvez afficher la syntaxe, les arguments de commande et l'utilisation des paramètres pour `oci-install.sh` :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --help`

. Exécutez le script d'installation :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh`

. Acceptez le contrat de licence et suivez les invites.

