---
permalink: install-linux/upgrading-remote-acquisition-units.html 
sidebar: sidebar 
keywords:  
summary: 'Après la mise à niveau du logiciel Insight Server, vous devez mettre à niveau votre logiciel d"acquisition à distance.' 
---
= Mise à niveau du logiciel de l'unité d'acquisition à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la mise à niveau du logiciel Insight Server, vous devez mettre à niveau votre logiciel d'acquisition à distance.

[NOTE]
====
Il est fortement recommandé de sauvegarder le coffre-fort et la base de données avant de mettre à niveau DWH.

Reportez-vous aux link:../config-admin\/security-management.html["Outil SecurityAdmin"] instructions pour plus d'informations sur le coffre-fort.

====


== Étapes

. Connectez-vous au serveur RAU (Remote acquisition Unit) à l'aide d'un compte avec privilèges sudo.
. Téléchargez le logiciel Insight RAU depuis le site du support NetApp.
. Accédez au répertoire de téléchargement et tapez la commande suivante :
+
`unzip oci-rau-<version>-linux-x86_64.zip`

+
Vérifiez que vous disposez du numéro de version correct du fichier d'installation.

. Vous pouvez afficher la syntaxe, les arguments de commande et l'utilisation des paramètres pour `oci-install.sh` :
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh --help`

. Exécutez le script d'installation :
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh`

. Acceptez le contrat de licence et suivez les invites.

