---
permalink: install-linux/upgrading-ethernet-monitoring-units.html 
sidebar: sidebar 
keywords:  
summary: Après avoir mis à niveau le logiciel du serveur Insight, vous devez mettre à niveau votre logiciel de surveillance ethernet. 
---
= Mise à niveau du logiciel de l'unité de surveillance Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir mis à niveau le logiciel du serveur Insight, vous devez mettre à niveau votre logiciel de surveillance ethernet.



== Description de la tâche

[NOTE]
====
L'unité de surveillance Ethernet (EMU) n'est pas prise en charge dans OnCommand Insight version 7.3.12 et ultérieure.

====


== Étapes

. Connectez-vous au serveur Ethernet Monitoring Unit (EMU) à l'aide d'un compte avec privilèges sudo.
. Téléchargez le logiciel Insight EMU sur le site du support NetApp.
. Accédez au répertoire de téléchargement et tapez la commande suivante :
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
Vérifiez que vous disposez du numéro de version correct du fichier d'installation.

. Vous pouvez afficher la syntaxe, les arguments de commande et l'utilisation des paramètres pour `oci-install.sh` :
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. Exécutez le script d'installation :
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. Acceptez le contrat de licence et suivez les invites.

