---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configuration du collecteur de données consul 
---
= Collecteur de données consul
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utilise ce collecteur de données pour collecter des mesures auprès de Consul.



== Installation

. Dans *observabilité > Collectors*, cliquez sur *+Data Collector*. Choisissez Consul.
+
Si vous n'avez pas configuré un agent pour la collecte, vous êtes invité à le faire link:task_config_telegraf_agent.html["installez un agent"] dans votre environnement.

+
Si un agent est déjà configuré, sélectionnez le système d'exploitation ou la plate-forme approprié et cliquez sur *Continuer*.

. Suivez les instructions de l'écran Configuration consul pour configurer le collecteur de données. Les instructions varient en fonction du type de système d'exploitation ou de plate-forme utilisé pour collecter des données.




== Configuration

Vous trouverez des informations dans le link:https://www.consul.io/docs/index.html["Documentation consul"].



== Objets et compteurs pour consul

Les objets suivants et leurs compteurs sont collectés :

[cols="<.<,<.<,<.<,<.<"]
|===
| Objet : | Identifiants : | Attributs : | Points de données : 


| Consul | Espace de noms
Vérifier ID
Nœud de service | IP du nœud
OS de nœud
UUID de nœud
Nom du nœud
Nom du service
Vérifiez le nom
ID de service
État | Primordial
Réussite
Avertissement 
|===


== Dépannage

Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] page.
