---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf, installation, install, kubernetes 
summary: Configuration du collecteur de données Kubernetes 
---
= Collecteur de données Kubernetes
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utilise ce collecteur de données pour recueillir les metrics du pod Kubernetes, des nœuds et des conteneurs.



== Installation

Pour obtenir des instructions d'installation de Kubernetes, consultez le link:task_config_telegraf_agent.html#kubernetes["Installation de l'agent"] page.


NOTE: L'information sur *kube-State-metrics* a été déplacée vers le link:task_config_telegraf_agent.html#kubernetes["Installation de l'agent"] page.



== Objets et compteurs

Les objets suivants et leurs compteurs sont collectés :

[cols="<.<,<.<,<.<,<.<"]
|===
| Objet : | Identifiants : | Attributs : | Points de données : 


| Conteneur Kubernetes | Espace de noms
Pod
Conteneur
Cluster | Nœud Kubernetes
Nom du nœud
OS de nœud
UUID de nœud
IP du nœud | Nanosecondes processeur
Utilisation du processeur Nanocores
Mémoire erreurs de page principale
Taille de l'ensemble résident mémoire (RSS)
Jeu de travail de mémoire
Anomalies de la page mémoire
Utilisation de la mémoire
Système de fichiers racine disponible
Capacité du système de fichiers racine
Système de fichiers racine utilisé 


| Nœud Kubernetes | Nœud Kubernetes
Cluster | Nom du nœud
OS de nœud
UUID de nœud
IP du nœud | Utilisation du processeur Nanocores
Utilisation CPU nanosecondes
Système de fichiers disponible
Total du système de fichiers
Système de fichiers utilisé
Mémoire disponible
Utilisation de la mémoire
Mémoire erreurs de page principale
Anomalies de la page mémoire
Taille de l'ensemble résident mémoire (RSS)
Jeu de travail de mémoire
Erreurs RX réseau (par seconde)
Octets RX réseau (par seconde)
Erreurs TX réseau (par seconde)
Octets TX réseau (par seconde)
Système de fichiers d'image d'exécution disponible
Système de fichiers d'image d'exécution utilisé
Capacité du système de fichiers d'image d'exécution 


| Pod Kubernetes | Espace de noms
Pod
Cluster | Nœud Kubernetes
Nom du nœud
IP du nœud
OS de nœud
UUID de nœud | Octets TX réseau (par seconde)
Erreurs TX réseau (par seconde)
Octets RX réseau (par seconde)
Erreurs RX réseau (par seconde) 


| Volume Kubernetes Pod | Volumétrie
Pod
Cluster
Espace de noms | Nœud Kubernetes
Nom du nœud
UUID de nœud
IP du nœud
OS de nœud | Disponibilité
Puissance
Utilisé 


| Conteneur du système Kubernetes | Conteneur système
Nœud Kubernetes
Cluster | Nom du nœud
IP du nœud
OS de nœud
UUID de nœud | Utilisation du processeur Nanocores
CPU usage Core nanosecondes
Mémoire erreurs de page principale
Anomalies de la page mémoire
Taille de l'ensemble résident mémoire (RSS)
Utilisation de la mémoire
Jeu de travail de mémoire
Système de fichiers racine disponible
Capacité du système de fichiers racine
Système de fichiers journaux disponible
Capacité du système de fichiers journaux 
|===


== Dépannage

[cols="2*"]
|===
| Problème : | Essayer : 


| J'ai exécuté la commande d'installation de l'agent Kubernetes, mais je ne vois pas de pod d'agent Telegraf s'exécutant via :

 sudo kubectl --namespace ci-monitoring get pods | Vérifiez s'il y a eu des erreurs lors du déploiement de DemonSet :

 sudo kubectl --namespace ci-monitoring décrire ds telegraf-ds

Si des erreurs sont liées à SecurityContextConstraints, procédez comme suit :

1. Générez le YAML Telegraf DemonSet

 sudo kubectl --namespace ci-monitoring get ds telegraf-ds -o yaml > /tmp/telegraf-ds.yaml

2. Arrêtez le service Telegraf

 sudo kubectl --namespace ci-monitoring delete ds telegraf-ds

3. Créez la contrainte de sécurité nécessaire (voir la section « Configuration de l'agent pour collecter des données »)

4. Recréez le jeu de démonstration Telegraf 


| J'ai configuré Telegraf pour obtenir des informations sur mon cluster Kubernetes, mais je ne vois aucune information dans Cloud Insights. Je vois des erreurs de "valeur de champ d'en-tête non valide" dans le fichier journal de Telegraf se rapportant au plug-in d'entrée kubernetes configuré. | Assurez-vous que le fichier bearer_token référencé ne comporte pas de saut de ligne arrière. Pour vérifier, exécutez la commande suivante et confirmez qu'elle renvoie 0 :

 queue -c1 <bearer_token_file> 
|===
Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] page.
