---
sidebar: sidebar 
permalink: task_config_telegraf_node.html 
keywords: telegraf, installation, install, node, host 
summary: Configuration du collecteur de données Flink 
---
= Collecte des données de nœud
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights collecte des metrics à partir du nœud sur lequel vous installez un agent.



== Installation

. Dans *observabilité > Collectors*, choisissez un système d'exploitation/une plate-forme. Notez que l'installation d'un collecteur de données d'intégration (Kubernetes, Docker, Apache, etc.) configure également la collecte des données du nœud.
. Suivez les instructions pour configurer l'agent. Les instructions varient en fonction du type de système d'exploitation ou de plate-forme utilisé pour collecter des données.




== Objets et compteurs

Les objets suivants et leurs compteurs sont collectés sous forme de metrics de nœud :

[cols="<.<,<.<,<.<,<.<"]
|===
| Objet : | Identifiants : | Attributs : | Points de données : 


| Système de fichiers de nœuds | UUID de nœud
Périphérique
Chemin
Type | IP du nœud
Nom du nœud
OS de nœud
Mode | Libre
Inodes libres
Inodes Total
Inodes utilisées
Total
Total utilisé
Utilisé 


| Disque de nœud | UUID de nœud
Disque | IP du nœud
Nom du nœud
OS de nœud | Temps E/S total
IOPS en cours
Octets lus (par seconde)
Temps de lecture total
Lectures (par seconde)
Temps E/S pondéré total
Octets d'écriture (par seconde)
Temps d'écriture total
Écritures (par seconde)
Longueur de la file d'attente du disque en cours
Heure d'écriture
Heure de lecture
Temps d'E/S. 


| Processeur des nœuds | UUID de nœud
CPU | IP du nœud
Nom du nœud
OS de nœud | Utilisation du processeur du système
Utilisation du processeur utilisateur
Utilisation de l'UC inactive
Utilisation du processeur
Interruption de l'utilisation de l'UC
Utilisation du processeur DPC 


| Nœud | UUID de nœud | IP du nœud
Nom du nœud
OS de nœud | Temps de démarrage du noyau
Commutateurs de contexte du noyau (par seconde)
Entropie du noyau disponible
Interruptions du noyau (par seconde)
Processus du noyau mis en place (par seconde)
Mémoire active
Mémoire disponible Total
Mémoire disponible
Mémoire tampon
Mémoire cache
Limite de validation de la mémoire
Mémoire validée en tant que
Mémoire sale
Mémoire libre
Mémoire haute capacité libre
Total mémoire haute
Mémoire taille de page énorme
Mémoire pages énormes libre
Mémoire pages énormes Total
Mémoire faible disponible
Mémoire faible Total
Mémoire mappée
Tables de pages mémoire
Mémoire partagée
Bloc de mémoire
Échange de mémoire en cache
Mémoire disponible
Total d'échange de mémoire
Mémoire totale
Mémoire utilisée Total
Mémoire utilisée
Bloc mémoire Vmalloc
Mémoire Vmalloc Total
Mémoire Vmalloc utilisée
Mémoire filaire
Total écriture mémoire
Attente de réécriture de mémoire
Défaillances du cache mémoire
Défauts de demande de mémoire zéro
Anomalies de la page mémoire
Pages mémoire
Mémoire non paginée
Mémoire paginée
Mémoire cache Core
Mémoire cache de secours Normal
Réserve de mémoire en veille
Erreurs de transition de mémoire
Processus bloqués
Processus morts
Processus inactifs
Traite la pagination
Processus en cours d'exécution
Processus en veille
Processus arrêtés
Total des processus
Traite le nombre total de threads
Processus inconnus
Processus Zombies
Longueur de la file d'attente du processeur
Échange libre
Total d'échange
Swap Total utilisé
Échange utilisé
Permuter
Remplacement
Disponibilité du système
CPU du numéro de système
Nombre d'utilisateurs système
Appels système 


| Réseau de nœuds | Interface réseau
UUID de nœud | Nom du nœud
IP du nœud
OS de nœud | Octets reçus
Octets envoyés
Paquets envoyés à haute voix rejetés
Erreurs de sortie de paquets
Paquets reçus rejetés
Paquets reçus erreurs
Paquets reçus
Paquets envoyés 
|===


== Configuration

Les informations de configuration et de dépannage se trouvent sur le link:task_config_telegraf_agent.html["Configuration d'un agent"] page.
